### ISSUE TITLE
How do you run this?

### ISSUE THREAD

**Issue by whateverusernameisnottaken** [abbodi1406/C2R-R2V-AIO#1]
Hi:

I don't understand how to use this. I'm quite tech savvy, but not clear on this. Can someone please explain how to run this on Windows 10 Pro?

**Comment by abbodi1406** [comment]
https://github.com/abbodi1406/WHD/raw/master/scripts/C2R-R2V-AIO_18.zip
extract, read `ReadMe-AIO.txt` for more info, run `C2R-R2V-AIO.cmd` as administrator

**Comment by whateverusernameisnottaken** [comment]
That doesn't tell me how to run it, does it. I copied it to a location, tried to run it in powershell. All I got was some output saying the parameters were incorrect. What parameters do I use?

**Comment by abbodi1406** [comment]
You never ran Windows command scripts before?
right-click on the script, and choose **Run as administrator**

**Comment by whateverusernameisnottaken** [comment]
No. Almost never. I never had need to. 

So, no parameters needed? Nothing? Just right click and run as Admin?

**Comment by whateverusernameisnottaken** [comment]
Getting this error. Ugh, I didn't know what Click to Run is, I just assumed this would work. My bad. So there's no way this will work on installs from physical media?



============================================================
Running C2R-R2V v18
============================================================

============================================================
Could not detect Office ClickToRun service...
============================================================

Press any key to exit...

**Comment by neuralpain** [comment]
> I'm quite tech savvy, but not clear on this.

Hi @whateverusernameisnottaken, if you just want to activate Office, I recommend that you use [`KMS_VL_ALL_AIO`](https://github.com/abbodi1406/KMS_VL_ALL_AIO/releases/latest).

- `C2R-R2V` is included in the script so you shouldn't need to run separately.
- Disable any other antivirus software (Windows Defender is ignored) and run the script.
- You will be prompted for Admin permission.

Hope this helps.

— NP

**Comment by whateverusernameisnottaken** [comment]
I need a legitimate activation. These machines are going to a charity. I have an OEM key, just don't have an OEM version of Office.

**Comment by ghost** [comment]
> I need a legitimate activation. These machines are going to a charity. I have an OEM key, just don't have an OEM version of Office.

@whateverusernameisnottaken You can acquire the installer for the OEM version of Office with [Office Tool Plus](https://github.com/YerongAI/Office-Tool).

**Comment by whateverusernameisnottaken** [comment]
Thanks, but apparently that tool doesn't support as far back as 2013. It only support 2016 and newer. It looks like a great tool, though. I'm definitely adding it to my toolkit.

**Comment by whalehub** [comment]
> Thanks, but apparently that tool doesn't support as far back as 2013. It only support 2016 and newer. It looks like a great tool, though. I'm definitely adding it to my toolkit.

I'd personally be hestitant to use Office 2013 since the EOL date for security updates is tomorrow: https://endoflife.date/office

**Comment by ghost** [comment]
> Thanks, but apparently that tool doesn't support as far back as 2013. It only support 2016 and newer. It looks like a great tool, though. I'm definitely adding it to my toolkit.

I'd personally be hesitant to use Office 2013 since the EOL date for security updates is tomorrow: https://endoflife.date/office

**Comment by whateverusernameisnottaken** [comment]
Aw darn. I guess I'll just leave these machines as they are then. Thanks for the help. Looks like a great tool otherwise.
