### ISSUE TITLE
Wrong License Converted

### ISSUE THREAD

**Issue by gpiece** [abbodi1406/C2R-R2V-AIO#2]
Hello. Thank you for your nice license convert script.

I using this script for Convert License Office 2016 ProPlus C2R Retail to Volume License.
But script converting 2016 ProPlus Retail to 2019 ProPlus VL. not 2016 ProPlus VL.

How can I resolve this problem?
If you want some information to this issue, i wll find and provide.

Sorry for bad english. Please help me. Thank you.

**Comment by abbodi1406** [comment]
It's designed like that, because Office 2019 is just Office 2016 v2
`Windows 10/11: Office 2016 products will be converted with corresponding Office 2019 licenses`

Office 2016 MSI VL is better than Office 2016 C2R

**Comment by gpiece** [comment]
OK i got it! thx to answer. have a nice day. :)
